#!/bin/bash

framework='react'
url='https://github.com/AGuekdjian/'
ext='.git'
name=$3
repoDef=$url$name$ext

check_exit_code() {
    if [ $? -ne 0 ]; then
    echo "Ah ocurrido un error: $1"
    exit 1
    fi
}

while getopts "r" opt; do
  case $opt in
    r)
      framework="react"
      ;;
    \?)
      echo "Uso: $0 [-r]  [otros argumentos]"
      exit 1
      ;;
  esac
done

echo '--------------------------------'
echo 'Moviendo al directorio indicado.'
echo '--------------------------------'
cd $2
printf "\n"

if [ $framework == "react" ]; then
	echo '-----------------------------------------'
	echo 'Inicializando proyecto en React con Vite.'
	echo '-----------------------------------------'
	npm create vite@latest $name -- --template $framework && cd $name
	check_exit_code "Error al crear el proyecto con vite"
	printf "\n"

	echo '------------------------------------------------'
    echo 'Moviendo al proyecto y inicializando git y repo.'
    echo '------------------------------------------------'
    npm i && git init && gh repo create $name --public
	check_exit_code "Error al crear el repositorio remoto"
	printf "\n"

	echo '-------------------------------------'
	echo 'Pusheando el proyecto al repositorio.'
	echo '-------------------------------------'
	git add . && git commit -m "First commit, add project."
	check_exit_code "Error al hacer el commit"
	printf "\n"
	
	echo '---------------------------------------'
	echo 'Estableciendo main como rama principal.'
	echo '---------------------------------------'
	git branch -M main
	check_exit_code "Error branch"
	printf "\n"

	echo '----------------------------------------'
	echo 'Subiendo el repositorio local al remoto.'
	echo '----------------------------------------'
	git remote add origin $repoDef
	check_exit_code "Error al subir el repositorio local al remoto"
	printf "\n"

	echo '------------'
	echo 'Pusheando...'
	echo '------------'
	git push -u origin main
	check_exit_code "Error al realizar push"
	printf "\n"

	echo '--------------------'
	echo 'Terminado con exito.'
	echo '--------------------'
fi
